site_name: Rancher Wiki
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
nav:
  - 证书: certs-rke.md
  - ACK/CCE 集群: import-advanced.md
  - Aliyun Node Driver: create-via-ecs.md
