site_name: Rancher Wiki
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
nav:
  - 证书: certs-rke.md
  - 普通导入 ACK/CCE: import-normal.md
  - KEv2 ACK/CCE: import-advanced.md
  - Aliyun Node Driver: create-via-ecs.md
